In [44]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train (1).csv

In [45]:
import io
import pandas as pd
train = pd.read_csv(io.BytesIO(uploaded['train.csv']))

In [46]:
train.head(3)

,id,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,0,36,Travel_Frequently,599,Research & Development,24,3,Medical,1,4,...,80,1,10,2,3,10,0,7,8,0
1,1,35,Travel_Rarely,921,Sales,8,3,Other,1,1,...,80,1,4,3,3,4,2,0,3,0
2,2,32,Travel_Rarely,718,Sales,26,3,Marketing,1,3,...,80,2,4,3,3,3,2,1,2,0

In [47]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test (1).csv

In [48]:
test = pd.read_csv(io.BytesIO(uploaded['test.csv']))

In [49]:
test.head(3)

,id,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1677,19,Non-Travel,992,Research & Development,1,1,Medical,1,4,...,4,80,0,1,2,2,1,0,0,0
1,1678,45,Travel_Rarely,1136,Sales,4,4,Marketing,1,3,...,3,80,1,7,3,3,2,2,2,2
2,1679,37,Travel_Rarely,155,Research & Development,13,3,Life Sciences,1,4,...,2,80,2,13,2,2,7,7,1,7

In [50]:
from google.colab import files
uploaded = files.upload()

Saving Attrition.csv to Attrition (1).csv

In [51]:
attrition = pd.read_csv(io.BytesIO(uploaded['Attrition.csv']))
attrition.head(3)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0

In [52]:
# rename column name
attrition.rename(columns = {'EmployeeNumber':'id'}, inplace = True)
attrition.head(3)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,id,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0

In [53]:
# replace yes/no
attrition.loc[attrition['Attrition'] == 'Yes','Attrition'] = 1
attrition.loc[attrition['Attrition'] == 'No','Attrition'] = 0
attrition['Attrition'].unique()

array([1, 0], dtype=object)

In [54]:
# concat data
attrition = attrition[train.columns.tolist()]
frames = [train, attrition]
train = pd.concat(frames)
train.reset_index( drop=True, inplace=True)
train

,id,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,0,36,Travel_Frequently,599,Research & Development,24,3,Medical,1,4,...,80,1,10,2,3,10,0,7,8,0
1,1,35,Travel_Rarely,921,Sales,8,3,Other,1,1,...,80,1,4,3,3,4,2,0,3,0
2,2,32,Travel_Rarely,718,Sales,26,3,Marketing,1,3,...,80,2,4,3,3,3,2,1,2,0
3,3,38,Travel_Rarely,1488,Research & Development,2,3,Medical,1,3,...,80,0,15,1,1,6,0,0,2,0
4,4,50,Travel_Rarely,1017,Research & Development,5,4,Medical,1,2,...,80,0,31,0,3,31,14,4,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3142,2061,36,Travel_Frequently,884,Research & Development,23,2,Medical,1,3,...,80,1,17,3,3,5,2,0,3,0
3143,2062,39,Travel_Rarely,613,Research & Development,6,1,Medical,1,4,...,80,1,9,5,3,7,7,1,7,0
3144,2064,27,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2,...,80,1,6,0,3,6,2,0,3,0
3145,2065,49,Travel_Frequently,1023,Sales,2,3,Medical,1,4,...,80,0,17,3,2,9,6,0,8,0
3146,2068,34,Travel_Rarely,628,Research & Development,8,3,Medical,1,2,...,80,0,6,3,4,4,3,1,2,0

In [55]:
features =  list(train.columns)
features.remove('id')
features.remove('Attrition')

target = 'Attrition'

In [56]:
columns_with_strings_as_values = list((train.dtypes[train.dtypes == 'object']).index)
columns_with_strings_as_values

['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime',
 'Attrition']

In [57]:
columns_with_strings_as_values =['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','Over18','OverTime']
columns_with_strings_as_values

['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [58]:
from sklearn.preprocessing import LabelEncoder
for col in columns_with_strings_as_values:
  le = LabelEncoder()
  train[col] = le.fit_transform(train[col])
  test[col] = le.fit_transform(test[col])

train.head(3)

,id,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,0,36,1,599,1,24,3,3,1,4,...,80,1,10,2,3,10,0,7,8,0
1,1,35,2,921,2,8,3,4,1,1,...,80,1,4,3,3,4,2,0,3,0
2,2,32,2,718,2,26,3,2,1,3,...,80,2,4,3,3,3,2,1,2,0

In [66]:
from sklearn.model_selection import StratifiedShuffleSplit
# Get the split indexes
strat_shuf_split = StratifiedShuffleSplit(n_splits=1,
                                          test_size=0.3,
                                          random_state=42)

train_idx, test_idx = next(strat_shuf_split.split(train[features],train.Attrition))

#create the dataframe
X_train = train.loc[train_idx, features]
y_train = train.loc[train_idx, 'Attrition']
y_train=y_train.astype('int')

X_test = train.loc[test_idx,features]
y_test = train.loc[test_idx,'Attrition']
y_test=y_test.astype('int')

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
# standard logistic regression
lr_l1 = LogisticRegressionCV(Cs=10,cv=4,penalty='l1',solver='liblinear').fit(X_train, y_train)

In [69]:
# predict the class and the probabiity for each
y_pred = list()
y_prob = list()
y_pred.append(pd.Series(lr_l1.predict(X_test)))
y_prob.append(pd.DataFrame(lr_l1.predict_proba(X_test)))


y_pred = pd.concat(y_pred, axis=1)
y_prob = pd.concat(y_prob, axis=1)

y_pred

     0
0    0
1    0
2    0
3    0
4    0
..  ..
940  0
941  0
942  0
943  0
944  0

[945 rows x 1 columns]

In [70]:
y_prob

            0         1
0    0.969882  0.030118
1    0.846872  0.153128
2    0.909618  0.090382
3    0.931423  0.068577
4    0.919225  0.080775
..        ...       ...
940  0.984153  0.015847
941  0.968868  0.031132
942  0.981646  0.018354
943  0.991006  0.008994
944  0.935974  0.064026

[945 rows x 2 columns]

In [71]:
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
from sklearn.preprocessing import label_binarize

metrics = list()

precision, recall, fscore, _ = score(y_test,y_pred, average='weighted')
accuracy = accuracy_score(y_test, y_pred)
metrics.append(pd.Series({'precision':precision,'recall':recall, 'fscore':fscore, 'accuracy':accuracy}))
  
metrics = pd.concat(metrics, axis=1)
metrics

                  0
precision  0.865202
recall     0.881481
fscore     0.855499
accuracy   0.881481

In [78]:
y_red = lr_l1.predict(test[features])
y_prob = lr_l1.predict_proba(test[features])
y_red
y_prob[:,1]

array([0.25496741, 0.27105556, 0.04618035, ..., 0.08697396, 0.06893396,
       0.00531005])

In [79]:
from google.colab import files
uploaded = files.upload()

Saving sample_submission.csv to sample_submission.csv

In [80]:
submission_log = pd.read_csv(io.BytesIO(uploaded['sample_submission.csv']))

In [81]:
submission_log.Attrition = y_prob[:,1]
submission_log

        id  Attrition
0     1677   0.254967
1     1678   0.271056
2     1679   0.046180
3     1680   0.249120
4     1681   0.237972
...    ...        ...
1114  2791   0.096727
1115  2792   0.013272
1116  2793   0.086974
1117  2794   0.068934
1118  2795   0.005310

[1119 rows x 2 columns]

In [82]:
submission_log.to_csv('submission_log.csv',index=False)